#NymPy Nedir?

In [ ]:
#NumPy açık kaynak kodlu ücretsiz ve özgür bir python kütüphanesidir.
#NumPy --> Numerical python anlamına gelir. Sayılarla daha hızlı matematik işlemler yapmamızı sağlar.
#NumPy kütüphanelerinin en temel elemanı array(dizi) dir.
#Arrayleri python dizilerinin çok boyutlu olanı gibi düşünebiliriz.
#Arrayler listelerden yaklaşık 50 kat daha hızlı çalışır.
#NumPy arraylerinin hızlı çalışmasının sebebi bu kütüphanenin çok büyük oranda c ve c++ ile yazılmış olması.

#NumPy Yüklenmesi

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


#NumPy'ı projeye dahil etme

In [ ]:
# import numpy
import numpy as np

#NumPy Array leri oluşturma

In [ ]:
# Arrayler çok boyutlu diziler gibi düşünülebilir.
# Arraylerin boyutları(dimension) vardır. 0d, 1d, 2d, 3d, 4d...

# Arrayleri oluşturmanın üç farklı yolu vardır.
# 1) Liste ya da tuple benzeri nesneleri array e döndürebiliriz.           np.array([1,2,3])
# 2) Built-in hazır fonksiyonları yardımıyla arrayler oluşturabiliriz.     np.arange(), np.linspace(), np.longspace() vb
# 3) Rastgele data üreterek                                                np.random modülün içindeki fonksşyonlar yardımıyla

In [ ]:
np.array(53)

array(53)

In [ ]:
arr0d = np.array([1,2,3])

In [ ]:
arr0d

array([1, 2, 3])

In [ ]:
arr1d = np.array([[1,2,3],[4,5,6]]) 
arr1d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[100,200,300]]])
arr2d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
arr5d = np.array([[8,7,9],[7,5,6,]])
arr5d

array([[8, 7, 9],
       [7, 5, 6]])

#Built-in Functionlarla Hızlıca NumPy Arrayleri Oluşturma

In [ ]:
# np.arrange() fonksiyonu ile hızlıca arrayler oluşturabiliriz. İstediğiniz sayı aralığında ardışık artan arrayler oluştururuz.
# Kullanımı aynen range() gibi. Start point dahil, end point dahil değil.
# Gene aynı range() fonksiyonlarında olduğu gibi (start-stop-step parametrelerini alır.)

In [ ]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(30,100,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96,
       98])

In [ ]:
# np.linspace() fonksiyonuyla da hızlıca arrayler oluşturulabilir.

In [ ]:
np.linspace(30,50,6, dtype=int) #end point dahil

array([30, 34, 38, 42, 46, 50])

In [ ]:
np.logspace(1,3,5) # 10^^1 ile 10^^3 arasında logaritmik artış yapan 5 tane veriden oluşan bir array

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [ ]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [ ]:
np.linspace(0,100,26)

array([  0.,   4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,
        44.,  48.,  52.,  56.,  60.,  64.,  68.,  72.,  76.,  80.,  84.,
        88.,  92.,  96., 100.])

In [ ]:
np.linspace(0,1000,26)

array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,
        360.,  400.,  440.,  480.,  520.,  560.,  600.,  640.,  680.,
        720.,  760.,  800.,  840.,  880.,  920.,  960., 1000.])

In [ ]:
np.zeros(5, dtype= int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,3), dtype= int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((5,8), dtype= int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5), dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones((2,3,5),dtype= int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
np.eye(5, dtype= int) # 5x5 birim matris 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.zeros((2,6), dtype= int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
# np.random() modülünü kullanarak rastgele verilerle arrayler oluşturmak.

In [ ]:
np.random.rand(3) # 3 tane 0-1 aralığında değerden oluşan bir array oluşturur

array([0.37455272, 0.63855212, 0.16058118])

In [ ]:
np.random.rand(2,5) # artı bir parantez almıyor. tuple değilmiş.

array([[0.32687298, 0.49912402, 0.28275705, 0.59306611, 0.19189471],
       [0.56615418, 0.37166927, 0.91768411, 0.92090853, 0.24151294]])

In [ ]:
np.random.rand(3)*10 #3 tane 0 ile 10 arasında random bir array oluşturur.

array([0.04294607, 1.40721403, 0.55351032])

In [ ]:
np.random.randint(15,50,5)

array([26, 32, 19, 18, 16])

In [ ]:
np.random.randint(0,100,(3,6))

array([[90,  3, 16, 82, 12, 36],
       [43, 28, 21, 17, 91, 55],
       [16, 28, 95, 62, 27, 70]])

In [ ]:
np.random.randint(0,100,200)

array([ 1, 73, 18, 89, 94, 15,  9, 19, 66, 89, 26, 68, 40, 57, 56, 62, 32,
       23, 28, 55, 58, 63, 49, 97, 86, 53, 22, 88,  5, 91, 49, 44, 49, 43,
       70, 29, 41, 41, 83, 77, 65, 88, 16,  0, 37, 11, 82, 63, 79, 33,  0,
        8, 39, 65, 91, 34, 19,  5,  7, 21, 53, 58, 10, 41, 56, 74, 11, 61,
       78, 19, 29, 36, 79, 87,  8, 89, 33, 14, 25, 75, 24, 58, 17, 94, 13,
       12, 38, 97, 84, 88, 62, 47, 32, 56, 73, 38, 88, 86, 78, 70, 67,  4,
       71, 50, 76,  5, 20, 45, 88, 62, 29, 55, 99, 40, 23, 97, 91, 11,  3,
       87,  5, 92, 82, 40, 70, 45, 46, 49, 98, 41, 51, 19, 74, 99, 50, 71,
       52, 89, 68, 21, 18, 62, 91, 98,  0, 32, 56, 86, 87, 69, 32, 98,  2,
       55, 73, 48, 64, 86,  9, 63, 51, 95, 57, 74,  7, 43, 50, 37, 39, 47,
       20, 52,  1, 31, 24, 81, 30, 54, 39,  0, 89, 21, 76, 10, 44, 92, 29,
       11, 40, 70, 82,  3, 54, 23, 91, 44, 40, 65, 31, 55])

In [ ]:
np.random.randint(0,50,(4,6))

array([[ 2,  1, 38, 28, 30,  5],
       [25, 29, 23, 36, 38,  5],
       [49, 14, 29, 21,  1, 44],
       [39, 32, 23, 15, 15, 41]])

#Array in Boyut Sayısını ve Shapeini Kontrol Etmek

In [ ]:
arr0d

array([1, 2, 3])

In [ ]:
arr1d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
# .ndim attribute ı ile arraylerimizin kaç bpyutlu olduğuna bakabiliriz.

In [ ]:
arr0d.ndim

1

In [ ]:
arr1d.ndim

2

In [ ]:
# .shape attribute ü ile arrayin shapeine bakılabilir.
# Bir arrayin shape i her boyuttaki ögelerinin sayısına eşittir.

In [ ]:
arr1d.shape

(2, 3)

In [ ]:
arr1d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
arr2d.shape

(2, 2, 3)

In [ ]:
arr4d = np.array([[ [1,2,3], [4,5,6], [10,25,35], [40,50,60]], [[10,20,30],[5,10,20],[11,22,33],[4,55,66] ]])
arr4d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [ 4, 55, 66]]])

In [ ]:
arr4d.ndim

3

In [ ]:
arr4d.shape

(2, 4, 3)

# NumPy Arraylerini İndexleme ve Öğelerine Erişme

In [ ]:
arr0d # 1 boyutlu arrayler listeler gibi düşünülebilir.

array([1, 2, 3])

In [ ]:
arr0d[0]

1

In [ ]:
arr2d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
arr2d[0][0][0] # arr2d[0,0,0]

1

In [ ]:
arr2d[0,1,2]

6

In [ ]:
arr2d[1,0,-1] # negatif indeksleme sondan olarak gösterir sondan 1. gibi

9

In [ ]:
arr8d = np.arange(53,62)
arr8d[4]

57

# NumPy Dizilerinin Maximum-Minimum Elemanlarına ve Bu Elemanların İndexlerine Erişme

In [ ]:
arr = np.random.randint(1,100,10)
arr

array([35, 14, 68, 10,  1, 57, 37,  1, 73, 63])

In [ ]:
arr.max()

73

In [ ]:
arr.argmax()

8

In [ ]:
arr.argmin()

4

#NumPy Arraylerinde Slicing(Dilimleme) Yapılabilir

In [ ]:
arr = np.arange(50,65)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [ ]:
arr[5:11]

array([55, 56, 57, 58, 59, 60])

In [ ]:
arr[-5:] # iki noktadan sonra boş bırakılırsa sonuna kadar gider

array([60, 61, 62, 63, 64])

In [ ]:
arr[2:10:2]

array([52, 54, 56, 58])

In [ ]:
arr[5:11] = 999 # Broadcasting
arr

array([ 50,  51,  52,  53,  54, 999, 999, 999, 999, 999, 999,  61,  62,
        63,  64])

In [ ]:
arr = np.arange(-30,11)
arr[5:19]

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

# Bir Arrayin Veri Türünü (Data Type ını) Kontrol Etme

In [ ]:
# .dtype attribute i ile data type ı kontrol edilebilir.

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr2 = np.arange(100, dtype= 'float')
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [ ]:
arr2.dtype

dtype('float64')

In [ ]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
arr3.dtype

dtype('<U1')

# Bir Arrayin Dtype'ını Değiştirme

In [ ]:
arr= np.array([1.2, 3.5, 5.8])
arr

array([1.2, 3.5, 5.8])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
# .astype() metodu ile arraylerin dtype ı değiştirilebilir

In [ ]:
arr.astype('int')

array([1, 3, 5])

In [ ]:
arr = np.array(['5','7','19','1','22','99','4'])
arr = arr.astype('int')
arr.dtype

dtype('int64')

In [ ]:
# 1.ders sonu