In [ ]:
import numpy as np

In [ ]:
arr4d = np.array([[ [1,2,3], [4,5,6], [10,25,35], [40,50,60]], [[10,20,30],[5,10,20],[11,22,33],[44,55,66] ]])
arr4d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [ 4, 55, 66]]])

In [ ]:
arr4d.ndim

3

In [ ]:
arr4d.shape

(2, 4, 3)

#Bir Array'i Reshape Etme (Yeniden Şekillendirme)

In [ ]:
# .reshape() metodu arrayin şeklini değştirmeye yeter.
# .rshape() yaparken toplam eleman sayısını sabit tutmaya dikkat etmeli.

In [ ]:
arr4d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [ 4, 55, 66]]])

In [ ]:
arr2d = arr4d.reshape(2,12)
arr2d

array([[ 1,  2,  3,  4,  5,  6, 10, 25, 35, 40, 50, 60],
       [10, 20, 30,  5, 10, 20, 11, 22, 33,  4, 55, 66]])

In [ ]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2d = arr.reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr3d = np.arange(30).reshape(2,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
# Bilinmeyen Boyut !!
# .rshape() metodu kullanılırken hesaplamak istemediğimiz boyut yerşne -1 yazıp otomatik hesaplattırabiliriz.

In [ ]:
arr3d = np.arange(120).reshape(5,2,-1)
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

In [ ]:
# 0-59 (59 dahil toplam 60 sayı) arasındaki tam sayılardan oluşan bir array oluşturun.
# Ardından bu array in shapeini değiştirerek istediğiniz shapelerde 3 boyutlu bir array elde edin. Daha sonra boyutuna ve shape ine bakın.
arr = np.arange(0,60).reshape(-1,3,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(4, 3, 5)

# Arrayleri Düzleştirme (Flatten)

In [ ]:
# Düzleştirme işlemi çok boyutlu bir arrayi bir boyutlu hale döndürmeye denir.
# Basitçe .reshape(-1) metoduyla yapılır.

In [ ]:
arr2d = np.arange(40).reshape(8,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
arr2d.shape

(8, 5)

In [ ]:
arr = arr2d.reshape(-1)

In [ ]:
arr3d = np.arange(60).reshape(-1,5,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [ ]:
arr3d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr = np.arange(30).reshape(2,3,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
arr = arr.reshape(-1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr.shape

(30,)

In [ ]:
arr.ndim

1

# Çok Boyutlu Array'lerde Iteration (Yineleme)

In [ ]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for x in arr1d:
  print(x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for x in arr2d:
  print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for x in arr2d:
  for y in x:
    print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
arr3d = np.arange(30).reshape(-1,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
for x in arr3d:
  for y in x:
    for z in y:
      print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


# Çok Boyutlu Arraylerde nditer() Kullanımı

In [ ]:
# For döngüsü arrayin boyuru kadar sayısa kullanılırsa ancak array'in bütün elemanlarına tek tek erişebiliriz.
# Çok boyutlu arraylerde nditer() fonksiyonunu bunun için geliştirebiliriz.
# For döngüsüne çok daha efektif ve hızlı bir şekilde tüm elemanları dönmenizi sağlar.

In [ ]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
for x in np.nditer(arr3d):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [ ]:
arr = np.arange(0,120).reshape(-1,2,20)
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
          32,  33,  34,  35,  36,  37,  38,  39]],

       [[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
          52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
          72,  73,  74,  75,  76,  77,  78,  79]],

       [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
          92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119]]])

In [ ]:
for x in np.nditer(arr):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119


# Array Elemanları Arasnda 4 İşlem


In [ ]:
arr1 = np.array([10,20,50,100])
arr2 = np.array([5,7,9,4]
                )

In [ ]:
arr1

array([ 10,  20,  50, 100])

In [ ]:
arr2

array([ 5,  7,  9, -1])

In [ ]:
arr1 + arr2

array([15, 27, 59, 99])

In [ ]:
arr1.__add__(arr2)

array([15, 27, 59, 99])

In [ ]:
arr1 - arr2

array([  5,  13,  41, 101])

In [ ]:
arr1.__sub__(arr2)

array([  5,  13,  41, 101])

In [ ]:
arr1 * arr2

array([  50,  140,  450, -100])

In [ ]:
arr1 ** arr2

array([          100000,       1280000000, 1953125000000000,
              100000000])

In [ ]:
arr1 / arr2

array([ 2.        ,  2.85714286,  5.55555556, 25.        ])

In [ ]:
arr1 // arr2

array([ 2,  2,  5, 25])

In [ ]:
arr1 % arr2

array([0, 6, 5, 0])

# Bir Arrayin Toplamına/Ortalamasına/Varyansına/Standart Sapmasına Bakma

In [ ]:
arr = np.random.randint(0,10,10)
arr

array([3, 7, 5, 9, 1, 0, 0, 5, 7, 8])

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.var() # karekökü stddir karekök = **0.5

10.05

In [ ]:
arr.std()

3.170173496829472

In [ ]:
arr

array([3, 7, 5, 9, 1, 0, 0, 5, 7, 8])

In [ ]:
np.sqrt(arr)

array([1.73205081, 2.64575131, 2.23606798, 3.        , 1.        ,
       0.        , 0.        , 2.23606798, 2.64575131, 2.82842712])

In [ ]:
# 0-100 (100 dahil) arası rastgele 10 tam sayıdan oluşan bir rray oluşturun ve oluşturulan arrayin sum/mean/var/std değerlerini inceleyin.
arr = np.random.randint(0,101,10)
arr

array([64, 27, 61, 45, 27, 18, 30, 33, 91, 26])

In [ ]:
arr.sum()

422

In [ ]:
arr.mean()

42.2

In [ ]:
arr.var()

476.16

In [ ]:
arr.std()

21.82109071517737

# NumPy Arraylerini Birleştirme (Concatenate)

In [ ]:
# NumPy arraylerini birleştirme işlemi .concatenate() fonksiyonu ile yapılır. Fonksiyonun içine liste halinde birleştirilecek arrayler verilir.
# np.concatenate([arr1,arr2] , axis =1(satır),0(sütun))

In [ ]:
arr1 = np.array([10,20,30,70])

In [ ]:
arr1

array([ 10,  20,  50, 100])

In [ ]:
arr2 = np.array([100,200,600,900])

In [ ]:
arr2

array([100, 200, 600, 900])

In [ ]:
np.concatenate([arr1,arr2], axis = 0) # axis eksendir.

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

In [ ]:
arr1 = np.array([[1,2,3],[5,6,7]])
arr2 = np.array([[100,200,300],[700,800,900]])

In [ ]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
arr2

array([[100, 200, 300],
       [700, 800, 900]])

In [ ]:
np.concatenate([arr1,arr2], axis = 1)

array([[  1,   2,   3, 100, 200, 300],
       [  5,   6,   7, 700, 800, 900]])

In [ ]:
np.concatenate([arr1,arr2], axis = 0)

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

# Arrayleri Stackleme (Yığınlama) İşlemleri

In [ ]:
# Concatenate işleminn hemen hemen aynısıdır tek farkı yeni bir boyut(eksen) üzerinde yığınlamalar yapmasıdır.

In [ ]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
arr2

array([[100, 200, 300],
       [700, 800, 900]])

In [ ]:
np.concatenate([arr1,arr2], axis = 0)

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

In [ ]:
np.stack([arr1, arr2], axis = 0)

array([[[  1,   2,   3],
        [  5,   6,   7]],

       [[100, 200, 300],
        [700, 800, 900]]])

In [ ]:
# np.hstack() --> satır boyunca yığınlama
# np.vstack() --> Sütun boyunca yığınlama

# NumPy Arraylerinde İndex Arama

In [ ]:
# Aradığımız değerlerin bulunduğu indexleri döndürmek için np.where() fonksiyonunu kullanırız.
# np.where() içerisine argüman olarak condition (şart) alır.

In [ ]:
arr = np.array([1,2,5,6,7,7,9,2,2,2])
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [ ]:
np.where(arr == 9) # arrayimizin kaçıncı indexindeki elemanlar dokuzdur.

(array([6]),)

In [ ]:
np.where(arr == 2)

(array([1, 7, 8, 9]),)

In [ ]:
np.where(arr%2 != 0) # Tek elemanların indexleri

(array([0, 2, 4, 5, 6]),)

# NumPy' da Random Kütüphanesi

In [ ]:
# Random diye ayrı bir kütüphane olmasının yanı sıra NumPy kütüphanesinin içinde random adında bir modül de bulunur.
# NumPy' ın içindeki random modülü normal random kütüphanesinden daha kapsamlıdır.

In [ ]:
#from numpy import random as rd

In [ ]:
import numpy as np

In [ ]:
np.random.rand() # 0-1 arası rastgele 1 tane sayı döndürür.

0.9960603883129029

In [ ]:
np.random.randn(5) # Normal dağılımdan random 5 tane veri çek.

array([-0.182662  , -0.89822048, -0.12245163, -1.37002678, -1.07601831])

In [ ]:
np.random.randint(low = 10, high = 30, size = 5)

array([15, 18, 22, 21, 27])

In [ ]:
np.random.randint(10,30,5)

array([11, 17, 26, 17, 29])

In [ ]:
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [ ]:
np.random.choice(arr)

5

In [ ]:
np.random.choice([3,-1,15])

15

In [ ]:
# Done.