In [ ]:
# 1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
import numpy as np
arr = np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [ ]:
# 2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve 
# son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr = np.random.rand(60)
arr

array([0.40171095, 0.57300779, 0.39766899, 0.23805876, 0.46240225,
       0.58910765, 0.65240701, 0.62958105, 0.15861892, 0.5953047 ,
       0.62717977, 0.9117416 , 0.8366472 , 0.24117062, 0.83757164,
       0.43893466, 0.05342548, 0.06310784, 0.54456339, 0.08923296,
       0.69414215, 0.12338642, 0.79276987, 0.79565544, 0.06351153,
       0.07277876, 0.06423014, 0.10055618, 0.02909514, 0.98284227,
       0.65171228, 0.24782306, 0.1305591 , 0.07791227, 0.15371429,
       0.47508544, 0.4338862 , 0.93355032, 0.70781474, 0.47428309,
       0.77467557, 0.45371178, 0.83691634, 0.64516239, 0.99227864,
       0.18921485, 0.04761076, 0.16856037, 0.89130494, 0.14021004,
       0.39587567, 0.48684983, 0.17891171, 0.34675494, 0.62317046,
       0.56532746, 0.60582643, 0.38939633, 0.33368824, 0.00697622])

In [ ]:
arr = arr.reshape(15,2,2)

In [ ]:
arr.shape

(15, 2, 2)

In [ ]:
arr.ndim

3

In [ ]:
# 3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. 
# Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr = np.linspace(0,9,20, dtype = int).reshape(4,5)
arr

array([[0, 0, 0, 1, 1],
       [2, 2, 3, 3, 4],
       [4, 5, 5, 6, 6],
       [7, 7, 8, 8, 9]])

In [ ]:
arr.reshape(-1)

array([0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9])

In [ ]:
# 4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları
# hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
arr = np.random.randint(10,50,35, dtype = int).reshape(7,5)
arr

array([[44, 30, 26, 26, 41],
       [48, 35, 37, 44, 14],
       [44, 27, 44, 26, 13],
       [13, 43, 34, 14, 28],
       [17, 44, 31, 49, 47],
       [31, 40, 17, 32, 26],
       [21, 44, 41, 22, 33]])

In [ ]:
for x in arr:
  for y in x:
    print(y)


44
30
26
26
41
48
35
37
44
14
44
27
44
26
13
13
43
34
14
28
17
44
31
49
47
31
40
17
32
26
21
44
41
22
33


In [ ]:
for x in np.nditer(arr):
  print(x)

44
30
26
26
41
48
35
37
44
14
44
27
44
26
13
13
43
34
14
28
17
44
31
49
47
31
40
17
32
26
21
44
41
22
33


In [ ]:
# 5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve 1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
# Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.
arr1d = np.array([5,10,15,20,25,30])
arr2d = np.array([1,2,3,4,5,6])
print ( arr1d + arr2d )
print ( arr1d - arr2d )
print ( arr1d * arr2d )
print ( arr1d / arr2d ) 

[ 6 12 18 24 30 36]
[ 4  8 12 16 20 24]
[  5  20  45  80 125 180]
[5. 5. 5. 5. 5. 5.]


In [ ]:
# 6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
arr = np.random.randint(0,101,10, dtype = int)
arr

array([58, 20, 35, 97, 27, 84, 77, 11, 91, 31])

In [ ]:
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.var())
print(arr.std())

531
53.1
97
927.89
30.46128690649822


In [ ]:
# 7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.
arr1d = np.arange(0,21)
arr2d = np.arange(500,531)
np.concatenate([ arr1d , arr2d ])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [ ]:
# 8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun.
# Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
arr1 = np.arange(15,51)
arr2 = np.arange(10,101)
arr3 = np.concatenate([ arr1 , arr2 ])
arr3[25:51] = 888
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
# 9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun.
# Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.
arr1 = np.arange(0,40).reshape(8,5)
arr2 = np.arange(320,360).reshape(8,5)
print(np.concatenate([ arr1 , arr2 ], axis = 0))
print(np.concatenate([ arr1 , arr2 ], axis = 1))

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]
[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]


In [ ]:
# 10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
np.concatenate([ arr1 , arr2 ], axis = 2)

AxisError: ignored

In [ ]:
np.stack([ arr1 , arr2 ], axis = 2)

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

In [ ]:
# 11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
arr = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(arr == 5)

(array([ 5, 13]),)

In [ ]:
# 12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
np.where(arr%2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

In [ ]:
# 13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
np.where(arr > 4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

In [ ]:
# 14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
np.where( arr%5 == 0)

(array([ 1,  2,  5, 13]),)

In [ ]:
# 15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin.
arr = np.random.randint(85,100,1, dtype = int)
arr

array([89])

In [ ]:
arr = np.arange(85,101)
np.random.choice(arr)

97

In [ ]:
# 16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
arr = np.random.randint(10,100,9, dtype = int).reshape(3,-1)
arr

array([[50, 62, 74],
       [38, 52, 93],
       [39, 49, 19]])

In [ ]:
# 17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
arr = np.arange(35,60)
np.random.choice(arr)

36

In [ ]:
# 18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.
arr = np.array([3,8,10,53,3,8,10,53,3,8]).reshape(2,5)
arr

array([[ 3,  8, 10, 53,  3],
       [ 8, 10, 53,  3,  8]])